# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = 'Gemfile.lock'
SPDX-FileCopyrightText = "2026 Kerrick Long <me@kerricklong.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = '**/snapshots/*.txt'
SPDX-FileCopyrightText = "2026 Kerrick Long <me@kerricklong.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = '**/snapshots/*.ansi'
SPDX-FileCopyrightText = "2026 Kerrick Long <me@kerricklong.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = 'doc/images/*'
SPDX-FileCopyrightText = "2026 Kerrick Long <me@kerricklong.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
